### ISSUE TITLE
[Feb 18th] Reinforcement Learning: An Introduction [meeting 2] 

### ISSUE THREAD

**Issue by charlieegan3** [computationclub/computationclub.github.io#123]
## Catch up

Following on from https://github.com/computationclub/computationclub.github.io/issues/119, write up here https://github.com/computationclub/computationclub.github.io/wiki/Reinforcement-Learning:-An-Introduction-%5BMeeting-1%5D

## The Meeting

**Where**: Ably Realtime

**When**: 18th Feb, 18:30-20:30

**What**: Chapters/sections 2.4-3.3 (*updated*)

Please react with the following:

* 👍 for I'm coming to this meeting
* 🎉 if you're also bringing snacks

## Todos

Before the meeting:

- [x] Announce the meeting on Buffer the Friday before if at least 4 are attending
- [x] Share the meeting on slack
- [x] Add meeting to website 

During the meeting:

- [x] Start exactly 7.5 mins into the 2 hour slot

After the meeting:

- [x] Write up the meeting on the wiki (add a link on the homepage)
- [x] Add the meeting to the website meetings.yml (and the link to the wiki)

**Comment by charlieegan3** [comment]
I've updated the suggested content to include up to 3.3 (end of)

**Comment by charlieegan3** [comment]
I've created a page on the wiki here: https://github.com/computationclub/computationclub.github.io/wiki/Reinforcement-Learning:-An-Introduction-%5BMeeting-2%5D
